const API = location.origin;
let site = {}, ws = null, myDeviceId = localStorage.getItem('hiliu_device_id') || '';
const $ = (s) => document.querySelector(s);
const toast = (t) => { const x=$('#toast'); if(!x)return; x.textContent=t; x.classList.add('show'); setTimeout(()=>x.classList.remove('show'),2200); };
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
async function api(path, opts={}){const r=await fetch(API+path,{credentials:'include',...opts});let b={};try{b=await r.json()}catch{}if(!r.ok)throw Error(b.message||'Yêu cầu thất bại');return b;}
async function loadSite(){site=await api('/api/site');const s=site.settings||{};$('#siteName').textContent=s.site_name||'HiLiu_Q';$('#tagline').textContent=s.site_tagline||'';['announcement'].forEach(k=>{const n=$('#announcement');if(s[k]){n.textContent=s[k];n.classList.remove('hidden')}});$('#donateName').textContent=s.donate_name||'';$('#donateAccount').textContent=s.donate_account||'';$('#donateBank').textContent=s.donate_bank||'';$('#donateContent').textContent=s.donate_content||'';$('#shorts').innerHTML=(site.shorteners||[]).map(x=>`<a class="ghost" href="/support/${x.id}" target="_blank">${escapeHtml(x.name)}</a>`).join(''); if(s.maintenance_mode==='1'){toast('Web đang ở chế độ bảo trì');}}
async function loadBooks(){const q=encodeURIComponent($('#search')?.value||'');const b=await api('/api/stories?q='+q);$('#books').innerHTML=(b.stories||[]).map(x=>`<article class="book glass"><img src="${escapeAttr(x.cover_url||'')}" alt=""><div class="inside"><b>${escapeHtml(x.title)}</b><div class="muted">${escapeHtml(x.author||'')} · ${escapeHtml(x.status||'')}</div><div style="margin-top:9px"><a class="primary" style="display:inline-block;padding:9px 11px;border-radius:10px;border:1px solid rgba(255,255,255,.12)" href="/reader?story=${x.id}">Đọc truyện</a></div></div></article>`).join('')||'<div class="muted">Chưa có truyện.</div>';}


async function submitStory(){try{const f=document.getElementById('sCover').files[0];const fd=new FormData();if(f)fd.append('cover',f);[['title','sTitle'],['alt_name','sAlt'],['author','sAuthor'],['artist','sArtist'],['assistant','sAssistant'],['translator','sTranslator'],['status','sStatus'],['description','sDesc']].forEach(([k,id])=>fd.append(k,document.getElementById(id).value));const b=await api('/api/stories/submit',{method:'POST',body:fd});toast('Đã gửi truyện chờ Admin duyệt · #'+b.story_id);}catch(e){toast(e.message)}}
async function setupGoogle(){try{if(!site.google_client_id)return;const box=document.getElementById('googleBox');if(!box)return;box.classList.remove('hidden');await new Promise((resolve,reject)=>{if(window.google?.accounts?.id)return resolve();const sc=document.createElement('script');sc.src='https://accounts.google.com/gsi/client';sc.onload=resolve;sc.onerror=reject;document.head.appendChild(sc)});google.accounts.id.initialize({client_id:site.google_client_id,callback:async r=>{try{await api('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:r.credential})});location.reload()}catch(e){document.getElementById('authMsg').textContent=e.message}}});box.innerHTML='';google.accounts.id.renderButton(box,{theme:'filled_black',size:'large',shape:'pill',text:'signin_with'});}catch(e){}}

function openAuth(){document.getElementById('authModal')?.classList.remove('hidden');}
function closeAuth(){document.getElementById('authModal')?.classList.add('hidden');}
async function doLogin(){try{const b=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identity:document.getElementById('aIdentity').value,password:document.getElementById('aPassword').value})});document.getElementById('authMsg').textContent='Đã đăng nhập: '+b.user.username;setTimeout(()=>location.reload(),500)}catch(e){document.getElementById('authMsg').textContent=e.message}}
async function doRegister(){try{const b=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('aIdentity').value,email:document.getElementById('aIdentity').value,password:document.getElementById('aPassword').value})});document.getElementById('authMsg').textContent='Đăng ký thành công: '+b.user.username;setTimeout(()=>location.reload(),500)}catch(e){document.getElementById('authMsg').textContent=e.message}}
document.getElementById('loginBtn')?.addEventListener('click',async()=>{const m=await api('/api/me').catch(()=>({user:null}));if(m.user?.role==='admin')location.href='/admin';else openAuth();});
async function login(){try{await api('/api/me').then(m=>{if(m.user){$('#loginBtn').textContent='👤 '+m.user.username;$('#userState').textContent='Đã đăng nhập: '+m.user.username;return null}return null})}catch(e){}}
$('#search')?.addEventListener('input',()=>{clearTimeout(window.__st);window.__st=setTimeout(loadBooks,250)});
async function createCode(){try{if(!myDeviceId){myDeviceId='dev_'+crypto.randomUUID();localStorage.setItem('hiliu_device_id',myDeviceId)}const b=await api('/api/devices/pair-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_id:myDeviceId})});$('#pairCode').textContent=b.code;toast('Mã kết nối có hiệu lực 5 phút');}catch(e){toast(e.message)}}
async function pairNow(){try{if(!myDeviceId)await createCode();const b=await api('/api/devices/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_id:myDeviceId,code:$('#pairInput').value.trim()})});toast('Đã ghép thiết bị '+b.paired_with)}catch(e){toast(e.message)}}
async function connectWS(){try{await api('/api/me');if(!myDeviceId){myDeviceId='dev_'+crypto.randomUUID();localStorage.setItem('hiliu_device_id',myDeviceId)}ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');ws.onopen=()=>ws.send(JSON.stringify({action:'auth_device',device_id:myDeviceId,name:navigator.userAgent.includes('Android')?'Android':'Browser',ua:navigator.userAgent}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='announcement'){const n=$('#announcement');n.textContent=m.text;n.classList.remove('hidden');toast('📢 '+m.text)}if(m.type==='device_registered')toast('Thiết bị đã kết nối');if(m.type==='devices')$('#onlineCount').textContent=(m.devices||[]).length;};ws.onclose=()=>setTimeout(connectWS,4000)}catch(e){}}
async function sendRequest(){try{const text=`📚 YÊU CẦU DỊCH HITên truyện/Chapter: ${$('#rTitle').value}\nNgôn ngữ nguồn: ${$('#rLang').value}\nSố ảnh/chapter: ${$('#rCount').value}\nNgôn ngữ đích: ${$('#rTarget').value}\nGhi chú: ${$('#rNote').value}`.replace('YÊU CẦU DỊCH','YÊU CẦU DỊCH\n');await navigator.clipboard.writeText(text);const b=await api('/api/translation-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});window.open('https://t.me/hiliu_q','_blank');toast(b.telegram_delivered?'Đã copy + gửi Telegram':'Đã copy + mở Telegram');}catch(e){toast(e.message)}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
window.scrollToId=scrollToId;window.createCode=createCode;window.pairNow=pairNow;window.sendRequest=sendRequest;window.submitStory=submitStory;window.openAuth=openAuth;window.closeAuth=closeAuth;window.doLogin=doLogin;window.doRegister=doRegister;
loadSite().then(setupGoogle).catch(e=>toast(e.message));loadBooks().catch(()=>{});login();connectWS();
